version: "3.8"

services:

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"

  client:
    container_name: client
    build:
      context: ./frontend/mcs-frontend
      dockerfile: Dockerfile
      target: base
    command: npm start

  api:
    container_name: api
    # stdin_open: true
    build:
      context: ./mcs_backend
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./mcs_backend/src:/home/node/app/src
      - ./mcs_backend/nodemon.json:/home/node/app/nodemon.json
    command: npm run dev
