version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: authdb
    
    restart: always

    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB_NAME
    
    ports:
      - $POSTGRES_LOCAL_PORT = $POSTGRES_DOCKER_PORT

    volumes:
      - ./postgres_authdb:/var/lib/postgresql/data

  backend:
    depends_on:
      - postgres

    # image:
    build: .
    container_name: mcs_backend
    
    restart: always

    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON:
        - POSTGRES_USER=$POSTGRES_USERNAME
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/$POSTGRES_DB_NAME
        - SPRING_DATASOURCE_USERNAME=$POSTGRES_USERNAME
        - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    
    volumes:
      - .:/mcs-app
